### ISSUE TITLE
Improve city "landing pages"

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregonnews#1]
Currently when clicking on a city, all we get is a giant list of search results, such as http://oregonnews.uoregon.edu/search/pages/results/?lccn=sn83025138&lccn=sn84022673&lccn=sn85042444&lccn=sn83045780&lccn=sn00063676&lccn=sn83045782&date1=1848&date2=1922&date1=&date2=&sequence=&ortext=&andte.  It might be nicer if that instead took users to a page like http://oregonnews.uoregon.edu/newspapers/, but with the list of newspapers for the selected city.

Since "city" isn't a piece of data in the core system, it might make sense to set that up so these pages wouldn't have to be built and managed manually.  (It would also give us more options for improvements in the future, such as limiting searches to a specific city's newspapers)

**Comment by srabun** [comment]
Thanks @jechols I will use the landing pages you mention above when I update the home page map. Good call!

**Comment by srabun** [comment]
update - the home page map cities now link to the city lists, for example, clicking on Astoria --> http://oregonnews.uoregon.edu/titles/places/oregon/clatsop/astoria/ This is good enough for me - should we close this ticket?

**Comment by jechols** [comment]
Ah, this is where it happened!  Okay, closing.
