### ISSUE TITLE
Create test batches

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/oregonnews#23]
We need at least two or three test batches with a good sampling of data.  We're thinking we should have the following:

- One batch with no TIFFs (or 0-byte TIFF files if the spec absolutely demands tiffs), to test our TIFF-free process doesn't have regressions
- One batch with full TIFFs (but only a few) just for variety's sake
- Many different newspapers, but with only a few pages from each - maybe 10-20 pages
- One batch with only one newspaper for a quick load test
- One batch with 10-20 newspapers (if this is doable) to have a single batch that loads solid test data
- Multiple different cities
- Multiple different counties
- No more than a few gigs total across all test batches so demos and dev environments are easy to spin up on a VM

Other stuff?

**Comment by srabun** [comment]
It's really time consuming to create new test batches, I don't think we will be able to get to this any time soon...

**Comment by jechols** [comment]
Actually I'm closing this anyway.  Now that we have a born-digital workflow, I've ended up building a fake batch builder for simple tests, and I have the tools to build real batches out of any pile of PDFs we have lying around.
