### ISSUE TITLE
pull attribution from metadata as opposed to batch name

### ISSUE THREAD

**Issue by srabun** [uoregon-libraries/oregonnews#27]
![screen shot 2014-12-05 at 9 36 38 am](https://cloud.githubusercontent.com/assets/8322525/5319922/615807ca-7c62-11e4-989b-c00c1438a91f.png)

See attribution tag circled in red - currently this data is being pulled from the marc org code in the batch name, for example "batch_oru_apple" - where "oru" is the org code for "University of Oregon Libraries"

Ideally we would like this tag to pull from the metadata field "SourceRepository" which can be found in the reel xml AND in the issue xmls as physicalLocation:

Reel xml:
![screen shot 2014-12-05 at 9 44 33 am](https://cloud.githubusercontent.com/assets/8322525/5320080/a3d64156-7c63-11e4-80f1-bbd61515025c.png)

Issue xml:
![screen shot 2014-12-05 at 9 45 30 am](https://cloud.githubusercontent.com/assets/8322525/5320085/ab46113c-7c63-11e4-9043-3fdd11b301a7.png)

**Comment by srabun** [comment]
I don't think we need to do this since we figured out the hack already?

**Comment by jechols** [comment]
I believe we hacked it in, but I don't know if it's the way forward.  Adding fake database records seems like a bad idea long-term, as opposed to coming up with a way to separate institution from attribution.

That said, this is good for our needs for now, and probably for a long time.  Doing it right might be something to worry about in open oni.
