### ISSUE TITLE
Partner attribution tag

### ISSUE THREAD

**Issue by srabun** [uoregon-libraries/oregonnews#4]
Linda has this on her to-do as well, but with hydra in play, feel free to look into this if time allows:

Some of our partners want an additional tag to be visible somewhere on the webpage when users are viewing their content in the viewer that says something like: "Digitized in partnership with: X organization"

similar to the "Image provided by: University of Oregon Libraries; Eugene, OR" that is present on the top left side of the viewer.

**Comment by srabun** [comment]
I think we have mastered this now. Can we close this ticket? Or would there be a better way to do this in the future (would require a major overhaul...)

**Comment by jechols** [comment]
I think we can close this.  Doing it right is already under discussion in #27.
