### ISSUE TITLE
Title duplication 

### ISSUE THREAD

**Issue by sseymore** [uoregon-libraries/oregonnews#50]
I'm seeing duplicate links for titles on the site:

http://oregonnews.uoregon.edu/titles/places/oregon/marion/salem/
http://oregonnews.uoregon.edu/titles/places/oregon/polk/dallas/
http://oregonnews.uoregon.edu/titles/places/oregon/polk/monmouth/

**Comment by jechols** [comment]
That's really odd.  I was hoping to say "Oh, LCCNs changed", but clearly that's not the case.  You want me or @lsat12357 to look into this?  How urgent is it?

**Comment by sseymore** [comment]
It’s not urgent- that is I’m the one who noticed it and not a user. I would like to prioritize the JP2s and get the next batches up first and then get to this. How does that sound? Either of you can handle it – given other tasks and availability. I’ll let you know if someone else points it out. : P

-Sarah

**Comment by jechols** [comment]
Works for me!
